In [1]:
from data_processor import DataProcessor
from nuplan.common.actor_state.state_representation import Point2D
from nuplan.planning.scenario_builder.nuplan_db.nuplan_scenario_utils import ScenarioMapping
from nuplan.planning.scenario_builder.nuplan_db.nuplan_scenario_builder import NuPlanScenarioBuilder
from nuplan.planning.scenario_builder.scenario_filter import ScenarioFilter
from nuplan.planning.utils.multithreading.worker_parallel import SingleMachineParallelExecutor
from diffusion_planner.data_process.utils import (convert_to_model_inputs,
get_scenario_map,
get_filter_parameters
)
import numpy as np


In [2]:
db_path = "/cailiu2/Diffusion-Planner/data/2021.10.21.14.43.30_veh-28_01244_01519.db" # single db file
db_path = "/share/data_cold/open_data/nuplan/data/cache/mini"  # multi db files
data_root = "/cailiu2/Diffusion-Planner/data/"
map_path = "/cailiu2/Diffusion-Planner/data/maps"
map_version = "nuplan-maps-v1.0"

save_processed_path = "/cailiu2/Diffusion-Planner/data/processed"
total_scenarios = 10
scenario_mapping = ScenarioMapping(scenario_map=get_scenario_map(), subsample_ratio_override=0.5)
builder = NuPlanScenarioBuilder(db_path, map_path, None, None, map_version, scenario_mapping = scenario_mapping)
worker = SingleMachineParallelExecutor(use_process_pool=True)
scenario_filter = ScenarioFilter(*get_filter_parameters(num_scenarios_per_type=30000,
                                                          limit_total_scenarios=total_scenarios))
scenarios = builder.get_scenarios(scenario_filter, worker)
del worker, builder, scenario_filter
processor = DataProcessor(scenarios)

In [11]:

ego_agent_past = None # inference no need ego_agent_past
print(scenarios[0])

'''
ego
'''
processor.scenario = scenarios[0]
ego_agent_past, time_stamps_past = processor.get_ego_agent()

print(ego_agent_past.shape)
print(time_stamps_past.shape)
print(time_stamps_past[1] - time_stamps_past[0])

neighbor_agent_past, neighbor_agents_types = processor.get_neighbor_agents()
print(len(neighbor_agent_past))
print(neighbor_agent_past[0][-1, :])
print(neighbor_agent_past[0][-2, :])
print(neighbor_agent_past[0][-3, :])
print(neighbor_agent_past[0][-4, :])
print(neighbor_agent_past[0].shape)

# ego_coords = Point2D(ego_state.rear_axle.x, ego_state.rear_axle.y)
# anchor_ego_state = np.array([ego_state.rear_axle.x, ego_state.rear_axle.y, ego_state.rear_axle.heading], dtype=np.float64)

torch.Size([21, 7])
torch.Size([21])
tensor(100014)
21
tensor([ 5.6000e+01, -1.0389e-01,  1.3635e-02,  2.2718e+00,  7.2730e-01,
         6.7506e-01,  3.3093e+05,  4.6911e+06])
tensor([ 5.5000e+01, -1.2660e+00, -8.2296e-01, -2.5866e+00,  8.2209e-01,
         9.2590e-01,  3.3095e+05,  4.6911e+06])
tensor([ 5.4000e+01, -1.0593e-02, -4.8961e-04, -3.0575e-01,  8.1148e-01,
         7.8747e-01,  3.3093e+05,  4.6911e+06])
tensor([ 5.3000e+01,  1.5506e-02, -1.0476e-02,  1.0675e+00,  7.7239e-01,
         7.0341e-01,  3.3093e+05,  4.6911e+06])
torch.Size([57, 8])


In [ ]:
"""
ego
"""
ego_state = processor.scenario.initial_ego_state
ego_coords = Point2D(ego_state.rear_axle.x, ego_state.rear_axle.y)
anchor_ego_state = np.array([ego_state.rear_axle.x, ego_state.rear_axle.y, ego_state.rear_axle.heading], dtype=np.float64)
print(ego_coords)
print(anchor_ego_state)




Point2D(x=330957.49299200956, y=4691143.579406448)
[3.30957493e+05 4.69114358e+06 5.43869085e-01]
